{{- if .Values.factory.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "esf.name" . }}-factory
automountServiceAccountToken: false
{{- end }}
{{- if .Values.console.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "esf.name" . }}-console
automountServiceAccountToken: false
{{- end }}
